### ISSUE TITLE
Теорема Штольца-2: нет доказательства

### ISSUE THREAD

**Issue by yeputons** [LDVSOFT/SPbAU-Cnzpkt#3]
Доказывается не так же, как первая, насколько мне известно. Есть на <a href="https://www.lektorium.tv/lecture/13941">записи</a>.

**Comment by LDVSOFT** [comment]
Теорема Штольца донаписана, но остались вопросы по случаю бесконечного a.

**Comment by LDVSOFT** [comment]
Why it is not closed?
